//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\maryannexe\documents\visual studio 2013\Projects\AntlrTest\AntlrTest\XcodeProject.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace Translator.Parser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="XcodeProjectParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public interface IXcodeProjectVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.proxy_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProxy_type([NotNull] XcodeProjectParser.Proxy_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.xc_configuration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXc_configuration_list([NotNull] XcodeProjectParser.Xc_configuration_listContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.source_tree"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSource_tree([NotNull] XcodeProjectParser.Source_treeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.settings"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSettings([NotNull] XcodeProjectParser.SettingsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.dst_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDst_path([NotNull] XcodeProjectParser.Dst_pathContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.build_phases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBuild_phases([NotNull] XcodeProjectParser.Build_phasesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.pbx_build_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPbx_build_file([NotNull] XcodeProjectParser.Pbx_build_fileContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.build_configurations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBuild_configurations([NotNull] XcodeProjectParser.Build_configurationsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.base_configuration_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBase_configuration_reference([NotNull] XcodeProjectParser.Base_configuration_referenceContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.pbx_target_dependency"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPbx_target_dependency([NotNull] XcodeProjectParser.Pbx_target_dependencyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.pbx_sources_build_phase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPbx_sources_build_phase([NotNull] XcodeProjectParser.Pbx_sources_build_phaseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.file_encoding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_encoding([NotNull] XcodeProjectParser.File_encodingContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_unused_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGcc_warn_unused_function([NotNull] XcodeProjectParser.Gcc_warn_unused_functionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] XcodeProjectParser.ValueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.build_action_mask"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBuild_action_mask([NotNull] XcodeProjectParser.Build_action_maskContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.objects"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjects([NotNull] XcodeProjectParser.ObjectsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_about_missing_field_initializers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGcc_warn_about_missing_field_initializers([NotNull] XcodeProjectParser.Gcc_warn_about_missing_field_initializersContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.xc_build_configuration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXc_build_configuration([NotNull] XcodeProjectParser.Xc_build_configurationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.targetS"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTargetS([NotNull] XcodeProjectParser.TargetSContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.file_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_ref([NotNull] XcodeProjectParser.File_refContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.pbx_resources_build_phase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPbx_resources_build_phase([NotNull] XcodeProjectParser.Pbx_resources_build_phaseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_unused_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGcc_warn_unused_variable([NotNull] XcodeProjectParser.Gcc_warn_unused_variableContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.default_configuration_is_visible"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefault_configuration_is_visible([NotNull] XcodeProjectParser.Default_configuration_is_visibleContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.provisioning_profile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProvisioning_profile([NotNull] XcodeProjectParser.Provisioning_profileContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.run_clang_static_analyzer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRun_clang_static_analyzer([NotNull] XcodeProjectParser.Run_clang_static_analyzerContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.iphoneos_deployment_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIphoneos_deployment_target([NotNull] XcodeProjectParser.Iphoneos_deployment_targetContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.project"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProject([NotNull] XcodeProjectParser.ProjectContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.code_sign_identity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCode_sign_identity([NotNull] XcodeProjectParser.Code_sign_identityContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.project_references"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProject_references([NotNull] XcodeProjectParser.Project_referencesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.known_regions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKnown_regions([NotNull] XcodeProjectParser.Known_regionsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.compatibility_version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompatibility_version([NotNull] XcodeProjectParser.Compatibility_versionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.dst_subfolder_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDst_subfolder_spec([NotNull] XcodeProjectParser.Dst_subfolder_specContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.remote_global_id_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRemote_global_id_string([NotNull] XcodeProjectParser.Remote_global_id_stringContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.shell_script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShell_script([NotNull] XcodeProjectParser.Shell_scriptContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.product_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProduct_reference([NotNull] XcodeProjectParser.Product_referenceContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray([NotNull] XcodeProjectParser.ArrayContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.pbx_copy_files_build_phase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPbx_copy_files_build_phase([NotNull] XcodeProjectParser.Pbx_copy_files_build_phaseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.container_portal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContainer_portal([NotNull] XcodeProjectParser.Container_portalContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.main_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMain_group([NotNull] XcodeProjectParser.Main_groupContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.build_configuration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBuild_configuration_list([NotNull] XcodeProjectParser.Build_configuration_listContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.product_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProduct_name([NotNull] XcodeProjectParser.Product_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.remote_info"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRemote_info([NotNull] XcodeProjectParser.Remote_infoContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_sign_compare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGcc_warn_sign_compare([NotNull] XcodeProjectParser.Gcc_warn_sign_compareContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChildren([NotNull] XcodeProjectParser.ChildrenContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.pbx_headers_build_phase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPbx_headers_build_phase([NotNull] XcodeProjectParser.Pbx_headers_build_phaseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.input_paths"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInput_paths([NotNull] XcodeProjectParser.Input_pathsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject([NotNull] XcodeProjectParser.ObjectContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.root_object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoot_object([NotNull] XcodeProjectParser.Root_objectContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.pbx_frameworks_build_phase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPbx_frameworks_build_phase([NotNull] XcodeProjectParser.Pbx_frameworks_build_phaseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.last_known_file_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLast_known_file_type([NotNull] XcodeProjectParser.Last_known_file_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_undeclared_selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGcc_warn_undeclared_selector([NotNull] XcodeProjectParser.Gcc_warn_undeclared_selectorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.dependencies"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDependencies([NotNull] XcodeProjectParser.DependenciesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.pbx_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPbx_group([NotNull] XcodeProjectParser.Pbx_groupContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_about_initializer_not_fully_bracketed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGcc_warn_about_initializer_not_fully_bracketed([NotNull] XcodeProjectParser.Gcc_warn_about_initializer_not_fully_bracketedContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.shell_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShell_path([NotNull] XcodeProjectParser.Shell_pathContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] XcodeProjectParser.NameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.pbx_native_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPbx_native_target([NotNull] XcodeProjectParser.Pbx_native_targetContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.isa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIsa([NotNull] XcodeProjectParser.IsaContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.right_side"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRight_side([NotNull] XcodeProjectParser.Right_sideContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.pbx_container_item_proxy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPbx_container_item_proxy([NotNull] XcodeProjectParser.Pbx_container_item_proxyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPath([NotNull] XcodeProjectParser.PathContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.product_install_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProduct_install_path([NotNull] XcodeProjectParser.Product_install_pathContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.pbx_shell_script_build_phase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPbx_shell_script_build_phase([NotNull] XcodeProjectParser.Pbx_shell_script_build_phaseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.product_ref_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProduct_ref_group([NotNull] XcodeProjectParser.Product_ref_groupContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.classes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClasses([NotNull] XcodeProjectParser.ClassesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.pbx_variant_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPbx_variant_group([NotNull] XcodeProjectParser.Pbx_variant_groupContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.files"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFiles([NotNull] XcodeProjectParser.FilesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_unused_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGcc_warn_unused_label([NotNull] XcodeProjectParser.Gcc_warn_unused_labelContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.development_region"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDevelopment_region([NotNull] XcodeProjectParser.Development_regionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.run_only_for_deployment_postprocessing"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRun_only_for_deployment_postprocessing([NotNull] XcodeProjectParser.Run_only_for_deployment_postprocessingContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.output_paths"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutput_paths([NotNull] XcodeProjectParser.Output_pathsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.left_side"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeft_side([NotNull] XcodeProjectParser.Left_sideContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.object_version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject_version([NotNull] XcodeProjectParser.Object_versionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.pbx_project"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPbx_project([NotNull] XcodeProjectParser.Pbx_projectContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.target_PROXY"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTarget_PROXY([NotNull] XcodeProjectParser.Target_PROXYContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.clang_enable_objc_arc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClang_enable_objc_arc([NotNull] XcodeProjectParser.Clang_enable_objc_arcContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.explicit_file_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicit_file_type([NotNull] XcodeProjectParser.Explicit_file_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.product_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProduct_type([NotNull] XcodeProjectParser.Product_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.has_scanned_for_encodings"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHas_scanned_for_encodings([NotNull] XcodeProjectParser.Has_scanned_for_encodingsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_shadow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGcc_warn_shadow([NotNull] XcodeProjectParser.Gcc_warn_shadowContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.default_configuration_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefault_configuration_name([NotNull] XcodeProjectParser.Default_configuration_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] XcodeProjectParser.AssignmentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.project_roots"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProject_roots([NotNull] XcodeProjectParser.Project_rootsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.pbx_file_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPbx_file_reference([NotNull] XcodeProjectParser.Pbx_file_referenceContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_about_return_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGcc_warn_about_return_type([NotNull] XcodeProjectParser.Gcc_warn_about_return_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.array_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_item([NotNull] XcodeProjectParser.Array_itemContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTarget([NotNull] XcodeProjectParser.TargetContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.pbx_aggregate_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPbx_aggregate_target([NotNull] XcodeProjectParser.Pbx_aggregate_targetContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributes([NotNull] XcodeProjectParser.AttributesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.project_dir_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProject_dir_path([NotNull] XcodeProjectParser.Project_dir_pathContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.archive_version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArchive_version([NotNull] XcodeProjectParser.Archive_versionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="XcodeProjectParser.build_settings"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBuild_settings([NotNull] XcodeProjectParser.Build_settingsContext context);
}
} // namespace AntlrTest
