//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\maryannexe\documents\visual studio 2013\Projects\AntlrTest\AntlrTest\XcodeProject.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace Translator.Parser {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="XcodeProjectParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public interface IXcodeProjectListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.proxy_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProxy_type([NotNull] XcodeProjectParser.Proxy_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.proxy_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProxy_type([NotNull] XcodeProjectParser.Proxy_typeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.xc_configuration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterXc_configuration_list([NotNull] XcodeProjectParser.Xc_configuration_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.xc_configuration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitXc_configuration_list([NotNull] XcodeProjectParser.Xc_configuration_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.source_tree"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSource_tree([NotNull] XcodeProjectParser.Source_treeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.source_tree"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSource_tree([NotNull] XcodeProjectParser.Source_treeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.settings"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSettings([NotNull] XcodeProjectParser.SettingsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.settings"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSettings([NotNull] XcodeProjectParser.SettingsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.dst_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDst_path([NotNull] XcodeProjectParser.Dst_pathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.dst_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDst_path([NotNull] XcodeProjectParser.Dst_pathContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.build_phases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBuild_phases([NotNull] XcodeProjectParser.Build_phasesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.build_phases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBuild_phases([NotNull] XcodeProjectParser.Build_phasesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.pbx_build_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPbx_build_file([NotNull] XcodeProjectParser.Pbx_build_fileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.pbx_build_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPbx_build_file([NotNull] XcodeProjectParser.Pbx_build_fileContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.build_configurations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBuild_configurations([NotNull] XcodeProjectParser.Build_configurationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.build_configurations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBuild_configurations([NotNull] XcodeProjectParser.Build_configurationsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.base_configuration_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBase_configuration_reference([NotNull] XcodeProjectParser.Base_configuration_referenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.base_configuration_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBase_configuration_reference([NotNull] XcodeProjectParser.Base_configuration_referenceContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.pbx_target_dependency"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPbx_target_dependency([NotNull] XcodeProjectParser.Pbx_target_dependencyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.pbx_target_dependency"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPbx_target_dependency([NotNull] XcodeProjectParser.Pbx_target_dependencyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.pbx_sources_build_phase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPbx_sources_build_phase([NotNull] XcodeProjectParser.Pbx_sources_build_phaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.pbx_sources_build_phase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPbx_sources_build_phase([NotNull] XcodeProjectParser.Pbx_sources_build_phaseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.file_encoding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile_encoding([NotNull] XcodeProjectParser.File_encodingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.file_encoding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile_encoding([NotNull] XcodeProjectParser.File_encodingContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_unused_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGcc_warn_unused_function([NotNull] XcodeProjectParser.Gcc_warn_unused_functionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_unused_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGcc_warn_unused_function([NotNull] XcodeProjectParser.Gcc_warn_unused_functionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] XcodeProjectParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] XcodeProjectParser.ValueContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.build_action_mask"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBuild_action_mask([NotNull] XcodeProjectParser.Build_action_maskContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.build_action_mask"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBuild_action_mask([NotNull] XcodeProjectParser.Build_action_maskContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.objects"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjects([NotNull] XcodeProjectParser.ObjectsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.objects"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjects([NotNull] XcodeProjectParser.ObjectsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_about_missing_field_initializers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGcc_warn_about_missing_field_initializers([NotNull] XcodeProjectParser.Gcc_warn_about_missing_field_initializersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_about_missing_field_initializers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGcc_warn_about_missing_field_initializers([NotNull] XcodeProjectParser.Gcc_warn_about_missing_field_initializersContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.xc_build_configuration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterXc_build_configuration([NotNull] XcodeProjectParser.Xc_build_configurationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.xc_build_configuration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitXc_build_configuration([NotNull] XcodeProjectParser.Xc_build_configurationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.targetS"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTargetS([NotNull] XcodeProjectParser.TargetSContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.targetS"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTargetS([NotNull] XcodeProjectParser.TargetSContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.file_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile_ref([NotNull] XcodeProjectParser.File_refContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.file_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile_ref([NotNull] XcodeProjectParser.File_refContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.pbx_resources_build_phase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPbx_resources_build_phase([NotNull] XcodeProjectParser.Pbx_resources_build_phaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.pbx_resources_build_phase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPbx_resources_build_phase([NotNull] XcodeProjectParser.Pbx_resources_build_phaseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_unused_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGcc_warn_unused_variable([NotNull] XcodeProjectParser.Gcc_warn_unused_variableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_unused_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGcc_warn_unused_variable([NotNull] XcodeProjectParser.Gcc_warn_unused_variableContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.default_configuration_is_visible"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefault_configuration_is_visible([NotNull] XcodeProjectParser.Default_configuration_is_visibleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.default_configuration_is_visible"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefault_configuration_is_visible([NotNull] XcodeProjectParser.Default_configuration_is_visibleContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.provisioning_profile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProvisioning_profile([NotNull] XcodeProjectParser.Provisioning_profileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.provisioning_profile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProvisioning_profile([NotNull] XcodeProjectParser.Provisioning_profileContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.run_clang_static_analyzer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRun_clang_static_analyzer([NotNull] XcodeProjectParser.Run_clang_static_analyzerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.run_clang_static_analyzer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRun_clang_static_analyzer([NotNull] XcodeProjectParser.Run_clang_static_analyzerContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.iphoneos_deployment_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIphoneos_deployment_target([NotNull] XcodeProjectParser.Iphoneos_deployment_targetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.iphoneos_deployment_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIphoneos_deployment_target([NotNull] XcodeProjectParser.Iphoneos_deployment_targetContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.project"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProject([NotNull] XcodeProjectParser.ProjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.project"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProject([NotNull] XcodeProjectParser.ProjectContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.code_sign_identity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCode_sign_identity([NotNull] XcodeProjectParser.Code_sign_identityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.code_sign_identity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCode_sign_identity([NotNull] XcodeProjectParser.Code_sign_identityContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.project_references"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProject_references([NotNull] XcodeProjectParser.Project_referencesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.project_references"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProject_references([NotNull] XcodeProjectParser.Project_referencesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.known_regions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKnown_regions([NotNull] XcodeProjectParser.Known_regionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.known_regions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKnown_regions([NotNull] XcodeProjectParser.Known_regionsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.compatibility_version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompatibility_version([NotNull] XcodeProjectParser.Compatibility_versionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.compatibility_version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompatibility_version([NotNull] XcodeProjectParser.Compatibility_versionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.dst_subfolder_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDst_subfolder_spec([NotNull] XcodeProjectParser.Dst_subfolder_specContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.dst_subfolder_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDst_subfolder_spec([NotNull] XcodeProjectParser.Dst_subfolder_specContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.remote_global_id_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRemote_global_id_string([NotNull] XcodeProjectParser.Remote_global_id_stringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.remote_global_id_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRemote_global_id_string([NotNull] XcodeProjectParser.Remote_global_id_stringContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.shell_script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShell_script([NotNull] XcodeProjectParser.Shell_scriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.shell_script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShell_script([NotNull] XcodeProjectParser.Shell_scriptContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.product_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProduct_reference([NotNull] XcodeProjectParser.Product_referenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.product_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProduct_reference([NotNull] XcodeProjectParser.Product_referenceContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray([NotNull] XcodeProjectParser.ArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray([NotNull] XcodeProjectParser.ArrayContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.pbx_copy_files_build_phase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPbx_copy_files_build_phase([NotNull] XcodeProjectParser.Pbx_copy_files_build_phaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.pbx_copy_files_build_phase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPbx_copy_files_build_phase([NotNull] XcodeProjectParser.Pbx_copy_files_build_phaseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.container_portal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContainer_portal([NotNull] XcodeProjectParser.Container_portalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.container_portal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContainer_portal([NotNull] XcodeProjectParser.Container_portalContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.main_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMain_group([NotNull] XcodeProjectParser.Main_groupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.main_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMain_group([NotNull] XcodeProjectParser.Main_groupContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.build_configuration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBuild_configuration_list([NotNull] XcodeProjectParser.Build_configuration_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.build_configuration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBuild_configuration_list([NotNull] XcodeProjectParser.Build_configuration_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.product_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProduct_name([NotNull] XcodeProjectParser.Product_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.product_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProduct_name([NotNull] XcodeProjectParser.Product_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.remote_info"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRemote_info([NotNull] XcodeProjectParser.Remote_infoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.remote_info"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRemote_info([NotNull] XcodeProjectParser.Remote_infoContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_sign_compare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGcc_warn_sign_compare([NotNull] XcodeProjectParser.Gcc_warn_sign_compareContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_sign_compare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGcc_warn_sign_compare([NotNull] XcodeProjectParser.Gcc_warn_sign_compareContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChildren([NotNull] XcodeProjectParser.ChildrenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.children"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChildren([NotNull] XcodeProjectParser.ChildrenContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.pbx_headers_build_phase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPbx_headers_build_phase([NotNull] XcodeProjectParser.Pbx_headers_build_phaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.pbx_headers_build_phase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPbx_headers_build_phase([NotNull] XcodeProjectParser.Pbx_headers_build_phaseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.input_paths"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInput_paths([NotNull] XcodeProjectParser.Input_pathsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.input_paths"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInput_paths([NotNull] XcodeProjectParser.Input_pathsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject([NotNull] XcodeProjectParser.ObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject([NotNull] XcodeProjectParser.ObjectContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.root_object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRoot_object([NotNull] XcodeProjectParser.Root_objectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.root_object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRoot_object([NotNull] XcodeProjectParser.Root_objectContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.pbx_frameworks_build_phase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPbx_frameworks_build_phase([NotNull] XcodeProjectParser.Pbx_frameworks_build_phaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.pbx_frameworks_build_phase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPbx_frameworks_build_phase([NotNull] XcodeProjectParser.Pbx_frameworks_build_phaseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.last_known_file_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLast_known_file_type([NotNull] XcodeProjectParser.Last_known_file_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.last_known_file_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLast_known_file_type([NotNull] XcodeProjectParser.Last_known_file_typeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_undeclared_selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGcc_warn_undeclared_selector([NotNull] XcodeProjectParser.Gcc_warn_undeclared_selectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_undeclared_selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGcc_warn_undeclared_selector([NotNull] XcodeProjectParser.Gcc_warn_undeclared_selectorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.dependencies"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDependencies([NotNull] XcodeProjectParser.DependenciesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.dependencies"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDependencies([NotNull] XcodeProjectParser.DependenciesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.pbx_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPbx_group([NotNull] XcodeProjectParser.Pbx_groupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.pbx_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPbx_group([NotNull] XcodeProjectParser.Pbx_groupContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_about_initializer_not_fully_bracketed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGcc_warn_about_initializer_not_fully_bracketed([NotNull] XcodeProjectParser.Gcc_warn_about_initializer_not_fully_bracketedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_about_initializer_not_fully_bracketed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGcc_warn_about_initializer_not_fully_bracketed([NotNull] XcodeProjectParser.Gcc_warn_about_initializer_not_fully_bracketedContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.shell_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShell_path([NotNull] XcodeProjectParser.Shell_pathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.shell_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShell_path([NotNull] XcodeProjectParser.Shell_pathContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] XcodeProjectParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] XcodeProjectParser.NameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.pbx_native_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPbx_native_target([NotNull] XcodeProjectParser.Pbx_native_targetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.pbx_native_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPbx_native_target([NotNull] XcodeProjectParser.Pbx_native_targetContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.isa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIsa([NotNull] XcodeProjectParser.IsaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.isa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIsa([NotNull] XcodeProjectParser.IsaContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.right_side"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRight_side([NotNull] XcodeProjectParser.Right_sideContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.right_side"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRight_side([NotNull] XcodeProjectParser.Right_sideContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.pbx_container_item_proxy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPbx_container_item_proxy([NotNull] XcodeProjectParser.Pbx_container_item_proxyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.pbx_container_item_proxy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPbx_container_item_proxy([NotNull] XcodeProjectParser.Pbx_container_item_proxyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPath([NotNull] XcodeProjectParser.PathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPath([NotNull] XcodeProjectParser.PathContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.product_install_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProduct_install_path([NotNull] XcodeProjectParser.Product_install_pathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.product_install_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProduct_install_path([NotNull] XcodeProjectParser.Product_install_pathContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.pbx_shell_script_build_phase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPbx_shell_script_build_phase([NotNull] XcodeProjectParser.Pbx_shell_script_build_phaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.pbx_shell_script_build_phase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPbx_shell_script_build_phase([NotNull] XcodeProjectParser.Pbx_shell_script_build_phaseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.product_ref_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProduct_ref_group([NotNull] XcodeProjectParser.Product_ref_groupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.product_ref_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProduct_ref_group([NotNull] XcodeProjectParser.Product_ref_groupContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.classes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClasses([NotNull] XcodeProjectParser.ClassesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.classes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClasses([NotNull] XcodeProjectParser.ClassesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.pbx_variant_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPbx_variant_group([NotNull] XcodeProjectParser.Pbx_variant_groupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.pbx_variant_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPbx_variant_group([NotNull] XcodeProjectParser.Pbx_variant_groupContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.files"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFiles([NotNull] XcodeProjectParser.FilesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.files"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFiles([NotNull] XcodeProjectParser.FilesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_unused_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGcc_warn_unused_label([NotNull] XcodeProjectParser.Gcc_warn_unused_labelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_unused_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGcc_warn_unused_label([NotNull] XcodeProjectParser.Gcc_warn_unused_labelContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.development_region"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDevelopment_region([NotNull] XcodeProjectParser.Development_regionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.development_region"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDevelopment_region([NotNull] XcodeProjectParser.Development_regionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.run_only_for_deployment_postprocessing"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRun_only_for_deployment_postprocessing([NotNull] XcodeProjectParser.Run_only_for_deployment_postprocessingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.run_only_for_deployment_postprocessing"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRun_only_for_deployment_postprocessing([NotNull] XcodeProjectParser.Run_only_for_deployment_postprocessingContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.output_paths"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutput_paths([NotNull] XcodeProjectParser.Output_pathsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.output_paths"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutput_paths([NotNull] XcodeProjectParser.Output_pathsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.left_side"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeft_side([NotNull] XcodeProjectParser.Left_sideContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.left_side"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeft_side([NotNull] XcodeProjectParser.Left_sideContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.object_version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject_version([NotNull] XcodeProjectParser.Object_versionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.object_version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject_version([NotNull] XcodeProjectParser.Object_versionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.pbx_project"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPbx_project([NotNull] XcodeProjectParser.Pbx_projectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.pbx_project"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPbx_project([NotNull] XcodeProjectParser.Pbx_projectContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.target_PROXY"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTarget_proxy([NotNull] XcodeProjectParser.Target_PROXYContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.target_PROXY"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTarget_PROXY([NotNull] XcodeProjectParser.Target_PROXYContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.clang_enable_objc_arc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClang_enable_objc_arc([NotNull] XcodeProjectParser.Clang_enable_objc_arcContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.clang_enable_objc_arc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClang_enable_objc_arc([NotNull] XcodeProjectParser.Clang_enable_objc_arcContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.explicit_file_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplicit_file_type([NotNull] XcodeProjectParser.Explicit_file_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.explicit_file_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplicit_file_type([NotNull] XcodeProjectParser.Explicit_file_typeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.product_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProduct_type([NotNull] XcodeProjectParser.Product_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.product_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProduct_type([NotNull] XcodeProjectParser.Product_typeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.has_scanned_for_encodings"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHas_scanned_for_encodings([NotNull] XcodeProjectParser.Has_scanned_for_encodingsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.has_scanned_for_encodings"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHas_scanned_for_encodings([NotNull] XcodeProjectParser.Has_scanned_for_encodingsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_shadow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGcc_warn_shadow([NotNull] XcodeProjectParser.Gcc_warn_shadowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_shadow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGcc_warn_shadow([NotNull] XcodeProjectParser.Gcc_warn_shadowContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.default_configuration_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefault_configuration_name([NotNull] XcodeProjectParser.Default_configuration_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.default_configuration_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefault_configuration_name([NotNull] XcodeProjectParser.Default_configuration_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] XcodeProjectParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] XcodeProjectParser.AssignmentContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.project_roots"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProject_roots([NotNull] XcodeProjectParser.Project_rootsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.project_roots"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProject_roots([NotNull] XcodeProjectParser.Project_rootsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.pbx_file_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPbx_file_reference([NotNull] XcodeProjectParser.Pbx_file_referenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.pbx_file_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPbx_file_reference([NotNull] XcodeProjectParser.Pbx_file_referenceContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_about_return_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGcc_warn_about_return_type([NotNull] XcodeProjectParser.Gcc_warn_about_return_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.gcc_warn_about_return_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGcc_warn_about_return_type([NotNull] XcodeProjectParser.Gcc_warn_about_return_typeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.array_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_item([NotNull] XcodeProjectParser.Array_itemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.array_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_item([NotNull] XcodeProjectParser.Array_itemContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTarget([NotNull] XcodeProjectParser.TargetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTarget([NotNull] XcodeProjectParser.TargetContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.pbx_aggregate_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPbx_aggregate_target([NotNull] XcodeProjectParser.Pbx_aggregate_targetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.pbx_aggregate_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPbx_aggregate_target([NotNull] XcodeProjectParser.Pbx_aggregate_targetContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributes([NotNull] XcodeProjectParser.AttributesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributes([NotNull] XcodeProjectParser.AttributesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.project_dir_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProject_dir_path([NotNull] XcodeProjectParser.Project_dir_pathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.project_dir_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProject_dir_path([NotNull] XcodeProjectParser.Project_dir_pathContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.archive_version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArchive_version([NotNull] XcodeProjectParser.Archive_versionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.archive_version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArchive_version([NotNull] XcodeProjectParser.Archive_versionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="XcodeProjectParser.build_settings"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBuild_settings([NotNull] XcodeProjectParser.Build_settingsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XcodeProjectParser.build_settings"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBuild_settings([NotNull] XcodeProjectParser.Build_settingsContext context);
}
} // namespace AntlrTest
